---
hostname: dotfiles-demo
description: |
  This is a vm for demo the dotfiles project.
readme: |
  In order to configure this computer, you need to setup the TERM
  capabilities to handle 24bit. Just compile the source with
  ```
  tic -x -o ~/.terminfo ~/.terminfo-24.src
  ```
