---
hostname: ceres
description: |
  This is my old and venerable laptop
readme: |
  In order to configure this computer, you need to setup the TERM
  capabilities to handle 24bit. Just compile the source with
  ```
  tic -x -o ~/.terminfo ~/.terminfo-24.src
  ```
